export const routeMetaMap = {
  dashboard: { menuId: 'DASHBOARD', menuUrl: '/dashboard' },
  users: { menuId: 'USERS', menuUrl: '/users' },
  departments: { menuId: 'DEPARTMENTS', menuUrl: '/departments' },
  jobGrades: { menuId: 'JOB_GRADES', menuUrl: '/job-grades' },
  positions: { menuId: 'POSITIONS', menuUrl: '/positions' },
  userPositions: { menuId: 'USER_POSITIONS', menuUrl: '/user-positions' },
  serviceAccesses: { menuId: 'SERVICE_ACCESSES', menuUrl: '/service-accesses' },
  groups: { menuId: 'GROUPS', menuUrl: '/groups' },
  groupMembers: { menuId: 'GROUP_MEMBERS', menuUrl: '/group-members' },
  menus: { menuId: 'MENUS', menuUrl: '/menus' },
  menuPermissions: { menuId: 'MENU_PERMISSIONS', menuUrl: '/menu-permissions' },
  codeGroups: { menuId: 'CODE_GROUPS', menuUrl: '/code-groups' },
  codes: { menuId: 'CODES', menuUrl: '/codes' },
  accounts: { menuId: 'ACCOUNT_INFO', menuUrl: '/trade/accounts' },
  items: { menuId: 'ITEM_SEARCH', menuUrl: '/trade/items' },
  watchlist: { menuId: 'WATCHLIST', menuUrl: '/trade/watchlist' },
  realtime: { menuId: 'REALTIME_MARKET', menuUrl: '/trade/realtime' },
} as const
