import {
  createDryRunTradeHistory,
  createWatchlistGroup,
  createWatchlistItem,
  deleteWatchlistGroup,
  deleteWatchlistItem,
  getItemDetail,
  getOrderableAmount,
  getRealtimeStatus,
  listAccounts,
  listDailyBalances,
  listItems,
  listKisCallLogs,
  listReconnectHistories,
  listTradeHistories,
  listWatchlist,
  listWatchlistGroups,
  publishRealtimeEvent,
  submitCashOrder,
  updateWatchlistItemMetadata,
  validateOrder,
} from '@/services/trade/api'

export {
  createDryRunTradeHistory,
  createWatchlistGroup,
  createWatchlistItem,
  deleteWatchlistGroup,
  deleteWatchlistItem,
  getItemDetail,
  getOrderableAmount,
  getRealtimeStatus as fetchRealtimeStatus,
  listAccounts,
  listDailyBalances,
  listItems,
  listKisCallLogs,
  listReconnectHistories,
  listTradeHistories,
  listWatchlist,
  listWatchlistGroups,
  publishRealtimeEvent,
  submitCashOrder,
  updateWatchlistItemMetadata,
  validateOrder,
}

export const fetchRealtimeQuotes = async () => []
