export const routeMetaMap = {
  adminUsers: { menuId: 'GROUPWARE_ADMIN_USERS', menuUrl: '/admin/users' },
  adminDepartments: { menuId: 'GROUPWARE_ADMIN_DEPARTMENTS', menuUrl: '/admin/departments' },
  adminJobGrades: { menuId: 'GROUPWARE_ADMIN_JOB_GRADES', menuUrl: '/admin/job-grades' },
  adminPositions: { menuId: 'GROUPWARE_ADMIN_POSITIONS', menuUrl: '/admin/positions' },
  adminUserPositions: { menuId: 'GROUPWARE_ADMIN_USER_POSITIONS', menuUrl: '/admin/user-positions' },
  adminServiceAccesses: { menuId: 'GROUPWARE_ADMIN_SERVICE_ACCESS', menuUrl: '/admin/service-accesses' },
  adminGroups: { menuId: 'GROUPWARE_ADMIN_GROUPS', menuUrl: '/admin/groups' },
  adminGroupMembers: { menuId: 'GROUPWARE_ADMIN_GROUPS', menuUrl: '/admin/group-members' },
  adminMenus: { menuId: 'GROUPWARE_ADMIN_MENUS', menuUrl: '/admin/menus' },
  adminMenuPermissions: { menuId: 'GROUPWARE_ADMIN_MENU_PERMISSIONS', menuUrl: '/admin/menu-permissions' },
  adminCodeGroups: { menuId: 'GROUPWARE_ADMIN_CODE_GROUPS', menuUrl: '/admin/code-groups' },
  adminCodes: { menuId: 'GROUPWARE_ADMIN_CODES', menuUrl: '/admin/codes' },
  chatPrivate: { menuId: 'GROUPWARE_CHAT_PRIVATE', menuUrl: '/groupware/chat/private' },
  chatGroup: { menuId: 'GROUPWARE_CHAT_GROUP', menuUrl: '/groupware/chat/groups' },
  chatRooms: { menuId: 'GROUPWARE_CHAT_ROOMS', menuUrl: '/groupware/chat/rooms' },
  schedules: { menuId: 'GROUPWARE_SCHEDULES', menuUrl: '/groupware/schedules' },
  projectSchedules: { menuId: 'GROUPWARE_PROJECT_SCHEDULES', menuUrl: '/groupware/project-schedules' },
  scheduleCosts: { menuId: 'GROUPWARE_SCHEDULE_COSTS', menuUrl: '/groupware/schedule-costs' },
  projects: { menuId: 'GROUPWARE_PROJECTS', menuUrl: '/groupware/projects' },
  projectTasks: { menuId: 'GROUPWARE_PROJECT_TASKS', menuUrl: '/groupware/project-tasks' },
  approvalDrafts: { menuId: 'GROUPWARE_APPROVAL_DRAFTS', menuUrl: '/groupware/approvals/drafts' },
  approvalInbox: { menuId: 'GROUPWARE_APPROVAL_INBOX', menuUrl: '/groupware/approvals/inbox' },
  approvalLines: { menuId: 'GROUPWARE_APPROVAL_LINES', menuUrl: '/groupware/approvals/lines' },
  notifications: { menuId: 'GROUPWARE_NOTIFICATIONS', menuUrl: '/groupware/notifications' },
  orgChart: { menuId: 'GROUPWARE_ORG_CHART', menuUrl: '/groupware/org-chart' },
} as const
