package com.upmudoum.trade.domain.master.vo;

public enum TradeMasterType {
    KOSPI,
    KOSDAQ,
    KONEX,
    ELW,
    ETF_ETN,
    DOMESTIC_INDEX,
    DOMESTIC_BOND,
    DOMESTIC_INDEX_FUTURE_OPTION,
    DOMESTIC_STOCK_FUTURE_OPTION,
    DOMESTIC_COMMODITY_FUTURE_OPTION,
    DOMESTIC_CME_FUTURE,
    DOMESTIC_EUREX_OPTION,
    OVERSEAS_STOCK,
    OVERSEAS_FUTURE,
    OVERSEAS_OPTION,
    OVERSEAS_INDEX,
    OVERSEAS_STOCK_OPTION,
    SECTOR_INDEX,
    THEME_INDEX,
    MEMBER
}
