import type { DataGridColumn } from '@/types/app'
import type { ErpReferenceDefinition, ErpResourceDefinition } from '@/types/erp'

export const ERP_BASE_PATH = '/api/erp'

const idColumn = (title = 'id', field = 'id'): DataGridColumn => ({
  title,
  field,
  editor: false,
  editable: false,
  width: 90,
})

const textColumn = (title: string, field: string, defaultValue = ''): DataGridColumn => ({
  title,
  field,
  editor: 'input',
  defaultValue,
})

const numberColumn = (title: string, field: string, defaultValue = 0): DataGridColumn => ({
  title,
  field,
  editor: 'number',
  defaultValue,
  hozAlign: 'right',
})

const boolColumn = (title: string, field: string, defaultValue = true): DataGridColumn => ({
  title,
  field,
  editor: 'tickCross',
  defaultValue,
  hozAlign: 'center',
  width: 110,
})

const selectColumn = (title: string, field: string, values: string[], defaultValue = values[0] ?? ''): DataGridColumn => ({
  title,
  field,
  editor: 'select',
  defaultValue,
  editorOptions: values.map((value) => ({ label: value, value })),
})

const dateColumn = (title: string, field: string): DataGridColumn => ({
  title,
  field,
  editor: 'input',
})

const readonlyText = (title: string, field: string): DataGridColumn => ({
  title,
  field,
  editor: false,
  editable: false,
})

const itemReference: ErpReferenceDefinition = {
  key: 'items',
  title: '품목 검색',
  endpoint: `${ERP_BASE_PATH}/items/search`,
  columns: ['id', 'code', 'name', 'unit', 'itemType', 'active'],
  filters: [
    { key: 'keyword', label: '검색어', placeholder: '품목 코드/명' },
    { key: 'itemType', label: '품목 유형', placeholder: 'FINISHED_GOOD' },
  ],
}

const warehouseReference: ErpReferenceDefinition = {
  key: 'warehouses',
  title: '창고 검색',
  endpoint: `${ERP_BASE_PATH}/warehouses`,
  columns: ['id', 'code', 'name', 'location', 'status'],
  filters: [{ key: 'keyword', label: '검색어', placeholder: '창고 코드/명' }],
}

const partnerReference: ErpReferenceDefinition = {
  key: 'partners',
  title: '거래처 검색',
  endpoint: `${ERP_BASE_PATH}/partners/search`,
  columns: ['id', 'code', 'name', 'businessNumber', 'partnerType', 'status'],
  filters: [
    { key: 'keyword', label: '검색어', placeholder: '거래처 코드/명' },
    { key: 'partnerType', label: '유형', placeholder: 'CUSTOMER' },
  ],
}

const processReference: ErpReferenceDefinition = {
  key: 'processes',
  title: '공정 검색',
  endpoint: `${ERP_BASE_PATH}/processes/search`,
  columns: ['id', 'code', 'name', 'processType', 'enabled'],
  filters: [{ key: 'processType', label: '공정 유형', placeholder: 'MANUFACTURING' }],
}

const routeReference: ErpReferenceDefinition = {
  key: 'routes',
  title: '라우트 검색',
  endpoint: `${ERP_BASE_PATH}/routes/search`,
  columns: ['id', 'code', 'name', 'itemId', 'itemCode', 'enabled'],
  filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
}

const equipmentReference: ErpReferenceDefinition = {
  key: 'equipments',
  title: '설비 검색',
  endpoint: `${ERP_BASE_PATH}/equipments/search`,
  columns: ['id', 'code', 'name', 'equipmentType', 'warehouseCode', 'status', 'enabled'],
  filters: [
    { key: 'equipmentType', label: '설비 유형', placeholder: 'CUTTER' },
    { key: 'status', label: '상태', placeholder: 'AVAILABLE' },
  ],
}

export const erpResourceDefinitions: Record<string, ErpResourceDefinition> = {
  items: {
    key: 'items',
    title: '품목 관리',
    description: '품목 생성, 수정, 비활성화를 관리한다.',
    listEndpoint: `${ERP_BASE_PATH}/items`,
    searchEndpoint: `${ERP_BASE_PATH}/items/search`,
    primaryAction: '품목 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      textColumn('unit', 'unit', 'EA'),
      selectColumn('itemType', 'itemType', ['RAW_MATERIAL', 'SEMI_FINISHED', 'FINISHED_GOOD', 'CONSUMABLE']),
      boolColumn('active', 'active'),
    ],
    filters: [
      { key: 'keyword', label: '검색어', placeholder: '품목 코드/명' },
      { key: 'itemType', label: '품목 유형', placeholder: 'RAW_MATERIAL' },
      { key: 'active', label: '활성', placeholder: 'true' },
    ],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/items`,
      updateEndpoint: `${ERP_BASE_PATH}/items`,
      softDeleteField: 'active',
      softDeleteValue: false,
    },
  },
  itemCategories: {
    key: 'itemCategories',
    title: '품목 분류 관리',
    description: '최대 3단계 품목 분류를 등록하고 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/item-categories`,
    primaryAction: '분류 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      numberColumn('parentCategoryId', 'parentCategoryId', 0),
      readonlyText('depth', 'depth'),
      boolColumn('active', 'active'),
    ],
    filters: [{ key: 'keyword', label: '검색어', placeholder: '분류 코드/명' }],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/item-categories`,
      readonly: false,
    },
  },
  partners: {
    key: 'partners',
    title: '거래처 관리',
    description: '거래처 생성, 수정, 상태 변경을 관리한다.',
    listEndpoint: `${ERP_BASE_PATH}/partners`,
    searchEndpoint: `${ERP_BASE_PATH}/partners/search`,
    primaryAction: '거래처 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      textColumn('businessNumber', 'businessNumber'),
      textColumn('partnerType', 'partnerType'),
      selectColumn('status', 'status', ['ACTIVE', 'SUSPENDED', 'INACTIVE']),
    ],
    filters: [
      { key: 'keyword', label: '검색어', placeholder: '거래처 코드/명' },
      { key: 'partnerType', label: '유형', placeholder: 'CUSTOMER' },
      { key: 'status', label: '상태', placeholder: 'ACTIVE' },
    ],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/partners`,
      updateEndpoint: `${ERP_BASE_PATH}/partners`,
      softDeleteField: 'status',
      softDeleteValue: 'INACTIVE',
    },
  },
  warehouses: {
    key: 'warehouses',
    title: '창고 관리',
    description: '창고 생성, 수정, 비활성화를 관리한다.',
    listEndpoint: `${ERP_BASE_PATH}/warehouses`,
    primaryAction: '창고 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      textColumn('location', 'location'),
      selectColumn('status', 'status', ['ACTIVE', 'INACTIVE']),
    ],
    filters: [{ key: 'keyword', label: '검색어', placeholder: '창고 코드/명' }],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/warehouses`,
      updateEndpoint: `${ERP_BASE_PATH}/warehouses`,
      softDeleteField: 'status',
      softDeleteValue: 'INACTIVE',
    },
  },
  safetyStocks: {
    key: 'safetyStocks',
    title: '안전재고 관리',
    description: '품목+창고별 안전재고를 upsert한다.',
    listEndpoint: `${ERP_BASE_PATH}/warehouse-safety-stocks`,
    primaryAction: '안전재고 저장',
    columns: [
      idColumn(),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      numberColumn('safetyQuantity', 'safetyQuantity'),
      boolColumn('active', 'active'),
    ],
    filters: [{ key: 'warehouseId', label: '창고 ID', placeholder: '1' }],
    references: [itemReference, warehouseReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/warehouse-safety-stocks`,
      softDeleteField: 'active',
      softDeleteValue: false,
    },
  },
  processes: {
    key: 'processes',
    title: '공정 관리',
    description: '생산 공정 기준정보를 관리한다.',
    listEndpoint: `${ERP_BASE_PATH}/processes`,
    searchEndpoint: `${ERP_BASE_PATH}/processes/search`,
    primaryAction: '공정 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      textColumn('processType', 'processType', 'MANUFACTURING'),
      textColumn('description', 'description'),
      boolColumn('enabled', 'enabled'),
    ],
    filters: [{ key: 'processType', label: '공정 유형', placeholder: 'MANUFACTURING' }],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/processes`,
      updateEndpoint: `${ERP_BASE_PATH}/processes`,
      softDeleteField: 'enabled',
      softDeleteValue: false,
    },
  },
  routes: {
    key: 'routes',
    title: '라우트 관리',
    description: '품목별 라우트 기준정보를 관리한다. Route step은 후속 상세 화면에서 확장한다.',
    listEndpoint: `${ERP_BASE_PATH}/routes`,
    searchEndpoint: `${ERP_BASE_PATH}/routes/search`,
    primaryAction: '라우트 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      boolColumn('enabled', 'enabled'),
    ],
    filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
    references: [itemReference, processReference, equipmentReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/routes`,
      updateEndpoint: `${ERP_BASE_PATH}/routes`,
      softDeleteField: 'enabled',
      softDeleteValue: false,
    },
  },
  equipments: {
    key: 'equipments',
    title: '설비 관리',
    description: '설비와 창고 연결 정보를 관리한다.',
    listEndpoint: `${ERP_BASE_PATH}/equipments`,
    searchEndpoint: `${ERP_BASE_PATH}/equipments/search`,
    primaryAction: '설비 등록',
    columns: [
      idColumn(),
      textColumn('code', 'code'),
      textColumn('name', 'name'),
      textColumn('equipmentType', 'equipmentType'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      textColumn('location', 'location'),
      selectColumn('status', 'status', ['AVAILABLE', 'UNAVAILABLE', 'MAINTENANCE']),
      boolColumn('enabled', 'enabled'),
    ],
    filters: [
      { key: 'equipmentType', label: '설비 유형', placeholder: 'CUTTER' },
      { key: 'status', label: '상태', placeholder: 'AVAILABLE' },
    ],
    references: [warehouseReference, processReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/equipments`,
      updateEndpoint: `${ERP_BASE_PATH}/equipments`,
      softDeleteField: 'enabled',
      softDeleteValue: false,
    },
  },
  standardCosts: {
    key: 'standardCosts',
    title: '표준원가 관리',
    description: '품목별 표준원가와 적용 기간을 등록한다.',
    listEndpoint: `${ERP_BASE_PATH}/costs/standard`,
    primaryAction: '표준원가 등록',
    columns: [
      idColumn(),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('standardCost', 'standardCost'),
      textColumn('currencyCode', 'currencyCode', 'KRW'),
      dateColumn('effectiveFrom', 'effectiveFrom'),
      dateColumn('effectiveTo', 'effectiveTo'),
      boolColumn('enabled', 'enabled'),
    ],
    filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
    references: [itemReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/costs/standard`,
      softDeleteField: 'enabled',
      softDeleteValue: false,
    },
  },
  inventoryBalances: {
    key: 'inventoryBalances',
    title: '재고 현황',
    description: '품목/창고별 현재 잔량을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/inventory/balances`,
    searchEndpoint: `${ERP_BASE_PATH}/inventory/balances/search`,
    primaryAction: '조회',
    columns: [
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      readonlyText('quantity', 'quantity'),
    ],
    filters: [
      { key: 'keyword', label: '검색어', placeholder: '품목 코드/명' },
      { key: 'warehouseId', label: '창고 ID', placeholder: '1' },
      { key: 'positiveOnly', label: '양수만', placeholder: 'true' },
    ],
    groupBy: 'warehouseCode',
    references: [itemReference, warehouseReference],
    save: { readonly: true },
  },
  inventoryMovements: {
    key: 'inventoryMovements',
    title: '재고 수불',
    description: '기초재고와 재고조정을 등록하고 수불을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/inventory/movements`,
    primaryAction: '기초/조정 등록',
    columns: [
      idColumn(),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      selectColumn('movementType', 'movementType', ['INITIAL', 'ADJUSTMENT_IN', 'ADJUSTMENT_OUT', 'ISSUE', 'RECEIPT']),
      numberColumn('quantity', 'quantity'),
      readonlyText('balanceAfter', 'balanceAfter'),
      textColumn('memo', 'memo'),
      readonlyText('occurredAt', 'occurredAt'),
    ],
    filters: [
      { key: 'itemId', label: '품목 ID', placeholder: '1' },
      { key: 'warehouseId', label: '창고 ID', placeholder: '1' },
    ],
    references: [itemReference, warehouseReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/inventory/adjustments`,
    },
  },
  lotBalances: {
    key: 'lotBalances',
    title: 'LOT 재고 현황',
    description: 'LOT별 창고 잔량을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/lots/balances`,
    searchEndpoint: `${ERP_BASE_PATH}/lots/balances/search`,
    primaryAction: '조회',
    columns: [
      idColumn(),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      readonlyText('lotId', 'lotId'),
      readonlyText('lotNo', 'lotNo'),
      readonlyText('quantity', 'quantity'),
      readonlyText('firstReceivedAt', 'firstReceivedAt'),
    ],
    filters: [
      { key: 'itemId', label: '품목 ID', placeholder: '1' },
      { key: 'warehouseId', label: '창고 ID', placeholder: '1' },
      { key: 'lotNo', label: 'LOT', placeholder: 'LOT-001' },
    ],
    groupBy: 'itemCode',
    references: [itemReference, warehouseReference],
    save: { readonly: true },
  },
  inventoryTransfers: {
    key: 'inventoryTransfers',
    title: '재고 이동',
    description: '창고 간 재고 이동을 등록하고 이력을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/inventory/transfers`,
    primaryAction: '재고 이동 등록',
    columns: [
      idColumn(),
      textColumn('transferNo', 'transferNo'),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('fromWarehouseId', 'fromWarehouseId'),
      readonlyText('fromWarehouseCode', 'fromWarehouseCode'),
      numberColumn('toWarehouseId', 'toWarehouseId'),
      readonlyText('toWarehouseCode', 'toWarehouseCode'),
      numberColumn('quantity', 'quantity'),
      textColumn('toLotNo', 'toLotNo'),
      textColumn('memo', 'memo'),
      readonlyText('transferredAt', 'transferredAt'),
    ],
    filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
    references: [itemReference, warehouseReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/inventory/transfers`,
    },
  },
  purchaseReceipts: {
    key: 'purchaseReceipts',
    title: '입고 관리',
    description: '매입 기반 입고를 등록하고 품목별 입고 라인을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/purchases/receipts/items`,
    primaryAction: '입고 등록',
    columns: [
      idColumn(),
      readonlyText('purchaseReceiptId', 'purchaseReceiptId'),
      numberColumn('partnerId', 'partnerId'),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      textColumn('lotNo', 'lotNo'),
      numberColumn('quantity', 'quantity'),
      numberColumn('unitPrice', 'unitPrice'),
      dateColumn('purchaseDate', 'purchaseDate'),
      readonlyText('supplyAmount', 'supplyAmount'),
    ],
    filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
    groupBy: 'purchaseReceiptId',
    references: [partnerReference, itemReference, warehouseReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/purchases/receipts`,
    },
  },
  salesShipments: {
    key: 'salesShipments',
    title: '출고 관리',
    description: '매출 기반 출고를 등록하고 품목별 출고 라인을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/sales/shipments/items`,
    primaryAction: '출고 등록',
    columns: [
      idColumn(),
      readonlyText('salesShipmentId', 'salesShipmentId'),
      numberColumn('partnerId', 'partnerId'),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('warehouseId', 'warehouseId'),
      readonlyText('warehouseCode', 'warehouseCode'),
      readonlyText('selectedLotNo', 'selectedLotNo'),
      numberColumn('quantity', 'quantity'),
      numberColumn('unitPrice', 'unitPrice'),
      dateColumn('salesDate', 'salesDate'),
      readonlyText('supplyAmount', 'supplyAmount'),
    ],
    filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
    groupBy: 'salesShipmentId',
    references: [partnerReference, itemReference, warehouseReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/sales/shipments`,
    },
  },
  boms: {
    key: 'boms',
    title: 'BOM 관리',
    description: 'BOM 버전을 등록하고 구성품은 후속 상세 화면에서 확장한다.',
    listEndpoint: `${ERP_BASE_PATH}/boms/versions`,
    primaryAction: 'BOM 버전 등록',
    columns: [
      idColumn(),
      readonlyText('bomId', 'bomId'),
      numberColumn('parentItemId', 'parentItemId'),
      readonlyText('parentItemCode', 'parentItemCode'),
      textColumn('versionNo', 'versionNo'),
      dateColumn('effectiveFrom', 'effectiveFrom'),
      dateColumn('effectiveTo', 'effectiveTo'),
      boolColumn('enabled', 'enabled'),
      boolColumn('defaultVersion', 'defaultVersion', false),
    ],
    filters: [{ key: 'parentItemId', label: '상위 품목 ID', placeholder: '1' }],
    references: [itemReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/boms/versions`,
    },
  },
  productionOrders: {
    key: 'productionOrders',
    title: '작업지시',
    description: '라우트/공정/설비가 연결된 생산지시를 등록하고 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/production/orders/search`,
    primaryAction: '작업지시 등록',
    columns: [
      idColumn(),
      textColumn('orderNo', 'orderNo'),
      numberColumn('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      numberColumn('bomVersionId', 'bomVersionId'),
      numberColumn('routeId', 'routeId'),
      readonlyText('routeCode', 'routeCode'),
      numberColumn('plannedProcessId', 'plannedProcessId'),
      readonlyText('plannedProcessCode', 'plannedProcessCode'),
      numberColumn('plannedEquipmentId', 'plannedEquipmentId'),
      readonlyText('plannedEquipmentCode', 'plannedEquipmentCode'),
      numberColumn('plannedQuantity', 'plannedQuantity'),
      dateColumn('dueDate', 'dueDate'),
      readonlyText('status', 'status'),
    ],
    filters: [
      { key: 'keyword', label: '검색어', placeholder: '지시번호/품목' },
      { key: 'status', label: '상태', placeholder: 'PLANNED' },
    ],
    references: [itemReference, routeReference, processReference, equipmentReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/production/orders`,
    },
  },
  productionResults: {
    key: 'productionResults',
    title: '생산실적',
    description: '작업지시 기준 생산실적을 등록하고 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/production/results/search`,
    primaryAction: '실적 등록',
    columns: [
      idColumn(),
      numberColumn('productionOrderId', 'productionOrderId'),
      readonlyText('orderNo', 'orderNo'),
      numberColumn('warehouseId', 'warehouseId'),
      numberColumn('goodQuantity', 'goodQuantity'),
      numberColumn('defectQuantity', 'defectQuantity'),
      textColumn('finishedLotNo', 'finishedLotNo'),
      numberColumn('routeId', 'routeId'),
      numberColumn('processId', 'processId'),
      readonlyText('processCode', 'processCode'),
      numberColumn('equipmentId', 'equipmentId'),
      readonlyText('equipmentCode', 'equipmentCode'),
      dateColumn('workStartedAt', 'workStartedAt'),
      dateColumn('workEndedAt', 'workEndedAt'),
      readonlyText('status', 'status'),
    ],
    filters: [
      { key: 'keyword', label: '검색어', placeholder: '지시번호/품목' },
      { key: 'status', label: '상태', placeholder: 'RECORDED' },
    ],
    groupBy: 'productionOrderId',
    references: [warehouseReference, routeReference, processReference, equipmentReference],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/production/orders/{productionOrderId}/results`,
    },
  },
  productionConsumptions: {
    key: 'productionConsumptions',
    title: '생산소모내역',
    description: '생산실적별 자재 소모 상세를 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/production/results/0/consumptions`,
    primaryAction: '조회',
    columns: [
      idColumn(),
      readonlyText('productionResultId', 'productionResultId'),
      readonlyText('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      readonlyText('plannedQuantity', 'plannedQuantity'),
      readonlyText('actualQuantity', 'actualQuantity'),
      readonlyText('adjustType', 'adjustType'),
    ],
    filters: [{ key: 'productionResultId', label: '실적 ID', placeholder: '1' }],
    save: { readonly: true },
  },
  actualCostHistories: {
    key: 'actualCostHistories',
    title: '실제원가 이력',
    description: 'ERP 이벤트별 실제원가 이력을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/costs/actual-histories`,
    primaryAction: '조회',
    columns: [
      idColumn(),
      readonlyText('itemId', 'itemId'),
      readonlyText('itemCode', 'itemCode'),
      readonlyText('referenceType', 'referenceType'),
      readonlyText('referenceId', 'referenceId'),
      readonlyText('unitCost', 'unitCost'),
      readonlyText('quantity', 'quantity'),
      readonlyText('appliedAt', 'appliedAt'),
    ],
    filters: [{ key: 'itemId', label: '품목 ID', placeholder: '1' }],
    references: [itemReference],
    save: { readonly: true },
  },
  accountingVouchers: {
    key: 'accountingVouchers',
    title: '회계전표',
    description: 'ERP 이벤트 기준 회계 전표를 등록하고 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/accounting/vouchers`,
    primaryAction: '전표 등록',
    columns: [
      idColumn(),
      textColumn('voucherNo', 'voucherNo'),
      dateColumn('voucherDate', 'voucherDate'),
      numberColumn('amount', 'amount'),
      textColumn('currencyCode', 'currencyCode', 'KRW'),
      textColumn('sourceEventType', 'sourceEventType'),
      numberColumn('sourceEventId', 'sourceEventId'),
      boolColumn('postImmediately', 'postImmediately', false),
      readonlyText('status', 'status'),
    ],
    filters: [
      { key: 'sourceEventType', label: '이벤트 유형', placeholder: 'SALE' },
      { key: 'sourceEventId', label: '이벤트 ID', placeholder: '1' },
    ],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/accounting/vouchers`,
    },
  },
  batchExecutions: {
    key: 'batchExecutions',
    title: '배치 실행',
    description: 'ERP 마감/집계 배치를 실행하고 이력을 조회한다.',
    listEndpoint: `${ERP_BASE_PATH}/batch-executions`,
    primaryAction: '배치 실행',
    columns: [
      readonlyText('executionId', 'executionId'),
      textColumn('jobName', 'jobName', 'inventorySummaryJob'),
      textColumn('parameters', 'parameters'),
      readonlyText('status', 'status'),
      readonlyText('exitCode', 'exitCode'),
      readonlyText('startTime', 'startTime'),
      readonlyText('endTime', 'endTime'),
    ],
    filters: [{ key: 'jobName', label: 'Job', placeholder: 'inventorySummaryJob' }],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/batch-executions`,
    },
  },
  printWorkInstructions: {
    key: 'printWorkInstructions',
    title: '작업지시서 출력',
    description: '작업지시서 렌더링 JSON을 documentKey로 조회한다.',
    documentEndpoint: `${ERP_BASE_PATH}/prints/work-instructions`,
    primaryAction: '출력 조회',
    columns: [readonlyText('documentType', 'documentType'), readonlyText('documentKey', 'documentKey'), readonlyText('barcodeValue', 'barcodeValue'), readonlyText('title', 'title')],
    filters: [{ key: 'documentKey', label: '문서 키', placeholder: 'WORK_INSTRUCTION-1' }],
    save: { readonly: true },
  },
  printIssueSlips: {
    key: 'printIssueSlips',
    title: '출고증 출력',
    description: '출고증 렌더링 JSON을 documentKey로 조회한다.',
    documentEndpoint: `${ERP_BASE_PATH}/prints/issue-slips`,
    primaryAction: '출력 조회',
    columns: [readonlyText('documentType', 'documentType'), readonlyText('documentKey', 'documentKey'), readonlyText('barcodeValue', 'barcodeValue'), readonlyText('title', 'title')],
    filters: [{ key: 'documentKey', label: '문서 키', placeholder: 'ISSUE_SLIP-1' }],
    save: { readonly: true },
  },
  printTransactionStatements: {
    key: 'printTransactionStatements',
    title: '거래명세서 출력',
    description: '거래명세서 렌더링 JSON을 documentKey로 조회한다.',
    documentEndpoint: `${ERP_BASE_PATH}/prints/transaction-statements`,
    primaryAction: '출력 조회',
    columns: [readonlyText('documentType', 'documentType'), readonlyText('documentKey', 'documentKey'), readonlyText('barcodeValue', 'barcodeValue'), readonlyText('title', 'title')],
    filters: [{ key: 'documentKey', label: '문서 키', placeholder: 'TRANSACTION_STATEMENT-1' }],
    save: { readonly: true },
  },
  printPurchaseOrders: {
    key: 'printPurchaseOrders',
    title: '발주서 출력',
    description: '발주서 렌더링 JSON을 documentKey로 조회한다.',
    documentEndpoint: `${ERP_BASE_PATH}/prints/purchase-orders`,
    primaryAction: '출력 조회',
    columns: [readonlyText('documentType', 'documentType'), readonlyText('documentKey', 'documentKey'), readonlyText('barcodeValue', 'barcodeValue'), readonlyText('title', 'title')],
    filters: [{ key: 'documentKey', label: '문서 키', placeholder: 'PURCHASE_ORDER-1' }],
    save: { readonly: true },
  },
  printGoodsReceipts: {
    key: 'printGoodsReceipts',
    title: '입고증 출력',
    description: '입고증 렌더링 JSON을 documentKey로 조회한다.',
    documentEndpoint: `${ERP_BASE_PATH}/prints/goods-receipts`,
    primaryAction: '출력 조회',
    columns: [readonlyText('documentType', 'documentType'), readonlyText('documentKey', 'documentKey'), readonlyText('barcodeValue', 'barcodeValue'), readonlyText('title', 'title')],
    filters: [{ key: 'documentKey', label: '문서 키', placeholder: 'GOODS_RECEIPT-1' }],
    save: { readonly: true },
  },
  printBarcodeLookup: {
    key: 'printBarcodeLookup',
    title: '바코드 출력 조회',
    description: '바코드 매핑을 관리하고 바코드값으로 출력 JSON을 조회한다.',
    documentEndpoint: `${ERP_BASE_PATH}/prints/barcodes`,
    listEndpoint: `${ERP_BASE_PATH}/prints/barcodes`,
    primaryAction: '바코드 저장',
    columns: [
      idColumn(),
      textColumn('barcodeValue', 'barcodeValue'),
      selectColumn('documentType', 'documentType', ['WORK_INSTRUCTION', 'ISSUE_SLIP', 'TRANSACTION_STATEMENT', 'PURCHASE_ORDER', 'GOODS_RECEIPT']),
      textColumn('documentKey', 'documentKey'),
      boolColumn('enabled', 'enabled'),
    ],
    filters: [
      { key: 'barcodeValue', label: '바코드', placeholder: 'WI-20260503-0007' },
      { key: 'documentType', label: '문서 유형', placeholder: 'WORK_INSTRUCTION' },
    ],
    save: {
      createEndpoint: `${ERP_BASE_PATH}/prints/barcodes`,
      updateEndpoint: `${ERP_BASE_PATH}/prints/barcodes`,
      deleteEndpoint: `${ERP_BASE_PATH}/prints/barcodes`,
      softDeleteField: 'enabled',
      softDeleteValue: false,
    },
  },
}

export const getErpResourceDefinition = (resourceKey: string) => erpResourceDefinitions[resourceKey]

export const createEmptyFilters = (definition: ErpResourceDefinition | undefined) =>
  Object.fromEntries((definition?.filters ?? []).map((filter) => [filter.key, '']))

export const getEndpointLabel = (definition: ErpResourceDefinition | undefined) =>
  definition?.searchEndpoint ?? definition?.listEndpoint ?? definition?.documentEndpoint ?? '연결 API 미정'
